// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveDownload():Promise<string>;

export function DownloadMaps(arg1:number):Promise<void>;

export function DownloadPercent():Promise<number>;

export function DownloadedBytes():Promise<number>;

export function DownloadedFiles():Promise<number>;

export function Exit():Promise<void>;

export function LocalEnabled():Promise<boolean>;

export function NeedsUpdate():Promise<boolean>;

export function OS():Promise<string>;

export function Play(arg1:boolean):Promise<void>;

export function Revision():Promise<number>;

export function ToggleLocal(arg1:boolean):Promise<void>;

export function TotalBytes():Promise<number>;

export function TotalFiles():Promise<number>;

export function Update():Promise<void>;

export function Version():Promise<string>;

export function Write(arg1:Array<number>):Promise<number>;
