// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveDownload() {
  return window['go']['main']['App']['ActiveDownload']();
}

export function DownloadMaps(arg1) {
  return window['go']['main']['App']['DownloadMaps'](arg1);
}

export function DownloadPercent() {
  return window['go']['main']['App']['DownloadPercent']();
}

export function DownloadedBytes() {
  return window['go']['main']['App']['DownloadedBytes']();
}

export function DownloadedFiles() {
  return window['go']['main']['App']['DownloadedFiles']();
}

export function Exit() {
  return window['go']['main']['App']['Exit']();
}

export function LocalEnabled() {
  return window['go']['main']['App']['LocalEnabled']();
}

export function NeedsUpdate() {
  return window['go']['main']['App']['NeedsUpdate']();
}

export function OS() {
  return window['go']['main']['App']['OS']();
}

export function Play(arg1) {
  return window['go']['main']['App']['Play'](arg1);
}

export function Revision() {
  return window['go']['main']['App']['Revision']();
}

export function ToggleLocal(arg1) {
  return window['go']['main']['App']['ToggleLocal'](arg1);
}

export function TotalBytes() {
  return window['go']['main']['App']['TotalBytes']();
}

export function TotalFiles() {
  return window['go']['main']['App']['TotalFiles']();
}

export function Update() {
  return window['go']['main']['App']['Update']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function Write(arg1) {
  return window['go']['main']['App']['Write'](arg1);
}
